app:
  build: ./
  volumes:
    - ./:/var/www/app
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=development
    - PORT=3000
    - SENDGRID_API_KEY=
  command:
    sh -c 'npm i && node server.js'